### ISSUE TITLE
Route and Listener setup tips

### ISSUE THREAD

**Issue by plindsay** [renoki-co/laravel-sns-events#5]
Very useful library 👍  Just a few things I noticed when implementing it -

I had to reference the route like this (note the slash at the beginning of the class)
`Route::any('/aws/sns', '\Rennokki\LaravelSnsEvents\Http\Controllers\SnsController@handle');`

I used the `event:generate` artisan command to generate the listeners and it added the wrong class declarations at the top of the listeners e.g.

change 
`use App\Events\Rennokki\LaravelSnsEvents\Events\SnsSubscriptionConfirmation` 
to 
`use Rennokki\LaravelSnsEvents\Events\SnsSubscriptionConfirmation`

change 
`use App\Events\Rennokki\LaravelSnsEvents\Events\SnsEvent` 
to 
`use Rennokki\LaravelSnsEvents\Events\SnsEvent`

**Comment by palomamtnez** [comment]
Hi @plindsay 
Thanks for your contribution 
Do you have any advice for the listener of the subscription confirmation?
I am trying to test this in my app, but for some reason, I don't receive any POST request.
At the moment, my listeners are set to log the event but nothing gets there.
I am wondering if it is something related with the authentication? 
Any help would be appreciated, thanks!

Note: My app is on staging so my subscription on SNS is set to `http://myproject.ecstaging.com/aws/sns`

**Comment by plindsay** [comment]
Hello,

No problem - was there anything in the logs to help you?

Also, have you remembered to whitelist the route in VerifyCsrfToken.php that receives the POST request?

Cheers,

Phil

**Comment by palomamtnez** [comment]
Yes! I worked with both logs and double-checked the whitelist. There was the problem. Uhhh! 
Thank you so much

**Comment by rennokki** [comment]
@plindsay Fixed in https://github.com/renoki-co/laravel-sns-events/commit/72146c1d6d518b9c705bc39b0a7d66cfcb508cb8
