### ISSUE TITLE
snsMessageIsValid method returns false in SnsController's handle

### ISSUE THREAD

**Issue by Biostate** [renoki-co/laravel-sns-events#92]
Hi, snsMessageIsValid method returns false in SnsController's handle. Problem is in 24. line of SnsController.php. I don't know why because SNS sends me correct values. 

Enviroment:
- PHP 8.1
- Laravel 9.19

To replicate this error:
1- Configure a rule set to receive email.
2- Send an email to that email.
3- Check the result in ngrok.

**Comment by reefki** [comment]
I got the same issue, there is a fix but has not been merged yet #91
